### ISSUE TITLE
in this project

### ISSUE THREAD

**Issue by hamadsajjad** [hamadsajjad/myfirst#4]
add a new button

**Comment by hamadali03** [comment]
add a pick

**Comment by hamadsajjad** [comment]
<img width="497" alt="Capture" src="https://github.com/hamadsajjad/myfirst/assets/167461592/a101775d-5e0e-45d0-9a24-44a44d1cc6fa">

**Comment by hamadali03** [comment]
<img width="497" alt="Capture" src="https://github.com/hamadsajjad/myfirst/assets/135126917/fa36099c-798b-44f5-91f2-307ce9d82e84">

i add button

**Comment by hamadali03** [comment]
i solve this issu #4

**Comment by hamadsajjad** [comment]
@
